Continue adding logging
mineiros-io/terramate pull request #139
Opened 2022-01-05 21:30 UTC by kassianh

Logging is done for any action or decision.

- Imperative statements are used for logging actions, simple statements for decisions
- Logging is done immediately before the action occurs
- Logging is done AFTER the decision has been made
	- Eg: In an if statement make log directly after entering saying what has happened
	- Simple statement - non-imperative. Eg: 'Changed' flag was set
- Not all fields are required
- Format is: 
	- level - trace, debug
	- time - Unix or RC3339
	- stack (optional) - Path of stack
	- action - Name of function where the action is found. With `()` to improve readibility
	- fileContext (optional) - Absolute path of file if reading a file
	- configFile (optional) - Config file associated with action
	- workingDirectory (optional) - Working directory - especially used if stack not relevant
	- path (optional) - Path/directory if relevant
	- command (optional) - Command if relevant
	- reference (optional) - Reference if relevant
	- message - Imperative/simple statement describing what is about to happen/has happened.. Period `.` at end to improve readibility.
- Things not to log:
	- return statements
	- errrors (are handled differently)
- Msg should not include variables - all msgf variables should be in a context field
Other relevant info should also be logged

2022-01-07 14:00 UTC, katcipis reviewed
Gave a few suggestions on naming/avoiding duplication. Overall LGTM since we can always improve later and it doesn't break anything. Will leave approval to @mariux so he can double check if it is enough as a starting point to help him.

2022-01-07 17:01 UTC, mariux commented
@kassianh lgtm... please rebase... ;) sorry i destroyed some ;) please check what changed

2022-01-07 17:12 UTC, mariux commented
@kassianh you can just globally accept all current changes when resolving.... i guess tests need to be adjusted after a rebase to main...

2022-01-07 17:13 UTC, mariux requested changes
pls rebase and fix tests afterwards

2022-01-07 17:39 UTC, katcipis commented
> @kassianh you can just globally accept all current changes when resolving.... i guess tests need to be adjusted after a rebase to main...

After we merge this: https://github.com/mineiros-io/terramate/pull/147
Adding logs should not affect tests anymore, so hopefully no need for test adjusting :-)

2022-01-07 22:32 UTC, kassianh commented on exported_locals.go
> +		Msg("Parse export as locals blocks.")
Good idea, thanks.

2022-01-09 22:57 UTC, mariux approved these changes
lgtm

2022-01-09 22:58 UTC, merged