docs: add genfile initial docs/spec
mineiros-io/terramate pull request #324
Opened 2022-04-27 10:33 UTC by katcipis

Initial spec for the new generate_file block.

2022-04-27 17:44 UTC, soerenmartius requested changes

2022-04-27 17:44 UTC, soerenmartius commented on docs/codegen/generate-file.md
> +Here is an example on how a JSON file can be created:
```suggestion
# File Generation

Terramate supports the generation of arbitrary text files referencing 
[Terramate defined data](../sharing-data.md).

File generation is done using `generate_file`
blocks in [Terramate configuration files](../config-overview.md).

The block **must** have a single label, that will be used to determine the
name of the generated file. Inside the block, the **content** attributes define
the string that will be written on the file.

The definition of the **content** attribute may include:

* Terramate Global references
* Terramate Metadata references
* Terramate function calls
* Expressions using string interpolation

The final evaluated **content** attribute **must** be a string.

Multiple `generate_file` blocks with the same label/filename will
result in an error.

Here is an example of how a JSON file can be created:
```

2022-04-27 17:44 UTC, soerenmartius commented on docs/codegen/overview.md
> +each integration scenario the best way possible. Currently we support:
```suggestion
each integration scenario in the best way possible. Currently, we support:
```

2022-04-27 19:57 UTC, soerenmartius approved these changes
lgtm! Good job!

2022-04-27 22:13 UTC, i4ki approved these changes
LGTM :rocket:

2022-04-28 12:37 UTC, mariux approved these changes
lgtm

2022-04-28 13:03 UTC, merged