chore: add basic command-line documentation
mineiros-io/terramate pull request #890
Opened 2023-03-30 13:10 UTC by i4ki

Documents the command-line features (specifically the upcoming Terramate Configuration File).

2023-04-02 09:03 UTC, soerenmartius requested changes

2023-04-02 09:03 UTC, soerenmartius commented on docs/cmdline.md
> +All sub-commands supports the `--help` flag as well for specific details.
```suggestion
All sub-commands support the `--help` flag as well for specific details.
```

2023-04-02 09:03 UTC, soerenmartius commented on docs/cmdline.md
> +version and system configuration. You can the command below in _PowerShell_ to
```suggestion
version and system configuration. You can use the command below in _PowerShell_ to 
```

2023-04-03 12:55 UTC, waxb approved these changes

2023-04-03 12:57 UTC, soerenmartius approved these changes
lgtm! great job

2023-04-03 13:14 UTC, merged